### ISSUE TITLE
ng serve error 

### ISSUE THREAD

**Issue by litchian18** [FaztWeb/angular-firestore-example#1]
**Below is the error message i get when run ng serve after npm install**

```
To disable this warning use "ng config -g cli.warnings.versionMismatch false".
module.js:549
    throw err;
    ^

Error: Cannot find module '@angular-devkit/core'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Chen Lit Chian\angular-project\z\angular-firestore-example\node_modules\@angular-devkit\schematics\src\tree\virtual.js:10:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by litchian18** [comment]
update `"@angular/cli" : "~6.0.1", `solve the problem.
